#!/bin/bash

vault login -method=userpass username=operations password=Password1
export CONSUL_HTTP_TOKEN=$(vault read -field token consul/creds/ops)
consul acl token read -self

cat <<EOF > /root/policies/jwt_auth_config.json
{
    "BoundAudiences": [
    "https://management.azure.com/"
    ],
    "BoundIssuer": "https://sts.windows.net/${ARM_TENANT_ID}/",
    "JWKSURL":"https://login.microsoftonline.com/${ARM_TENANT_ID}/discovery/v2.0/keys",
    "ClaimMappings": {
        "id": "xms_mirid"
    }
}
EOF
consul acl auth-method create -name azure -type jwt -config @/root/policies/jwt_auth_config.json
consul acl binding-rule create -method=azure -bind-type=role -bind-name=app-role -selector='value.xms_mirid matches `.*/app`'
consul acl binding-rule create -method=azure -bind-type=role -bind-name=web-role -selector='value.xms_mirid matches `.*/web`'

exit 0