#!/bin/bash

set-workdir /root/terraform

pubkey=$(cat ~/.ssh/id_rsa.pub)
cat << EOF > /root/terraform/vault/terraform.tfvars
ssh_public_key = "$(cat ~/.ssh/id_rsa.pub)"
EOF


cd /root/terraform/vault
terraform init

cd /root/terraform/hcs
terraform init

exit 0
