#!/bin/bash

sleep 10

if [ -f /tmp/skip-check ]; then
    rm /tmp/skip-check
    exit 0
fi

vault_lb=$(terraform output -state=/root/terraform/vault/terraform.tfstate vault_lb)
consul_lb=$(terraform output -state /root/terraform/hcs/terraform.tfstate consul_url)


exit 0



