#!/bin/bash


cd /root/terraform/vault
terraform apply -refresh=false -auto-approve > /root/terraform/vault/terraform.out
sleep 10

cd /root/terraform/hcs
terraform apply -refresh=false -auto-approve > /root/terraform/hcs/terraform.out
sleep 10

exit 0
